version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: gin-redis
    restart: "always"
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - gin-redis-volume:/data

volumes:
  gin-redis-volume:
